manifest:
  remotes:
    - name: kgmossey
      url-base: https://github.com/kgmossey
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: kgmossey
      revision: master
      import: app/west.yml
  self:
    path: config
